# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

batch:
  fast-fail: false

  # build-graph:

  #   - identifier: build1
  #     env:
  #       variables:
  #         BUILD_ID: build1
  #     ignore-failure: false

  #   - identifier: build2
  #     buildspec: build2.yml
  #     env:
  #       variables:
  #         BUILD_ID: build2
  #     depend-on:
  #       - build1

  #   - identifier: build3
  #     env:
  #       variables:
  #         BUILD_ID: build3
  #     depend-on:
  #       - build2
      
  # build-list:

  #   - identifier: build1
  #     env:
  #       variables:
  #         BUILD_ID: build1
  #     ignore-failure: false

  #   - identifier: build2
  #     buildspec: build2.yml
  #     env:
  #       variables:
  #         BUILD_ID: build2
  #     ignore-failure: true

  build-matrix:
    static:
      ignore-failure: false
    dynamic:
      buildspec: 
        - matrix1.yml
        - matrix2.yml
      env:
        variables:
          MY_VAR:
            - VALUE1
            
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - git branch --show-current 
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo "MY_VAR is ${MY_VAR}"
  post_build:
    commands:

artifacts:
  files:
    - '**/*'
